"""Zip the rendered site for hand-carried distribution: doc-publish bundle

Produces dist/thesis-site-<date>.zip containing the rendered site plus a README.txt
noting the build date and that search needs the bundled instructions' local server
(the rest of the site works straight from the unzipped folder).
"""
from __future__ import annotations

import datetime
import sys
import zipfile

from .. import config

README = """Thesis site - rendered {date}

Open index.html in a browser; navigation, figures and maths work directly from this
folder. The search box is the one feature that needs a local server (browsers block
its index file under file://): from this folder run

    python -m http.server 8123

and browse to http://localhost:8123/ instead.

Generated by `doc-publish site` from the LaTeX source of {source}.
The LaTeX is the source of truth; this bundle is a build product.
"""


def main(argv: list[str] | None = None) -> int:
    try:
        root = config.site_build_dir()
        out = config.dist_dir(create=True)
        source = config.source_label()
    except config.ConfigError as exc:
        print(exc, file=sys.stderr)
        return 2

    if not (root / "index.html").exists():
        print(f"{root}/index.html not found - run `doc-publish site` first", file=sys.stderr)
        return 2
    date = datetime.date.today().isoformat()
    dest = out / f"thesis-site-{date}.zip"
    with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("README.txt", README.format(date=date, source=source))
        for p in sorted(root.rglob("*")):
            if p.is_file():
                z.write(p, p.relative_to(root))
    print(f"wrote {dest} ({dest.stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
