"""Copy the published artefacts into the publish repo: thesis-agent publish

    thesis-agent publish              site + corpus into $THESIS_PUBLISH_REPO
    thesis-agent publish --site-only  just the rendered HTML

Writes files and stops. It does not stage, commit, push, or touch git in any way - the
result is meant to be read as a diff before it becomes permanent, because the publish
repo is intended to go public and a public repo's history cannot be taken back.

Everything written here is built from the **public** corpus. The guards below are
deliberately redundant with that: the cost of a draft note reaching a public repo is
not symmetric with the cost of an extra check.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from .. import config

#: Filenames that must never be copied, whatever else changes upstream.
NEVER_COPY = {"corpus_draft.md", "annotations.json"}

#: Marker the draft build writes for each retained source comment.
DRAFT_MARKER = "> [draft note]"

#: Text extensions worth scanning for leaked drafting state before copying.
SCANNED = {".html", ".md", ".json", ".qmd", ".txt", ".js"}

README = """# Published thesis site

Generated by `thesis-agent publish` from the LaTeX source of {source}. The LaTeX is the
source of truth; everything in this directory is a build product and is overwritten on
the next run - edit the LaTeX, not these files.

Built from the **public** corpus: LaTeX source comments, provisional numbers and open
supervisor questions are excluded by construction and re-checked on every publish.

- `site/` - the rendered site. Open `index.html`; search needs a local server.
- `corpus/` - the flattened text and its label/figure maps, for anything downstream.
"""


class GuardFailure(RuntimeError):
    """A payload file looks like drafting state. Nothing is copied."""


def _scan(paths: list[Path]) -> None:
    """Refuse the whole publish if any file carries drafting state.

    Checked by name and by content: a renamed draft corpus still carries the marker,
    and a file that acquired the marker some other way is equally not publishable.
    """
    for path in paths:
        if path.name in NEVER_COPY:
            raise GuardFailure(f"{path} is a draft artefact and must never be published")
        if path.suffix.lower() not in SCANNED:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if DRAFT_MARKER in text:
            raise GuardFailure(
                f"{path} contains '{DRAFT_MARKER}' - this is the draft build. "
                f"Rebuild with CORPUS_MODE=public and re-run.")


def _copy_tree(src: Path, dest: Path) -> int:
    """Mirror `src` onto `dest`, removing what is no longer generated.

    Stale pages are the failure this prevents: a section removed from the corpus that
    lingers as an orphaned HTML file is exactly what the leak checks exist to catch,
    and it would survive a plain copy indefinitely.
    """
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    return sum(1 for p in dest.rglob("*") if p.is_file())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="thesis-agent publish")
    ap.add_argument("--site-only", action="store_true",
                    help="copy the rendered site but not the corpus")
    ap.add_argument("--subdir", default="site",
                    help="directory within the publish repo (default: site)")
    args = ap.parse_args(argv)

    try:
        target = config.publish_repo()
        rendered = config.site_build_dir()
        build = config.build_dir()
        source = config.source_label()
        mode = config.corpus_mode()
    except config.ConfigError as exc:
        print(exc, file=sys.stderr)
        return 2

    if mode != "public":
        print(f"CORPUS_MODE={mode} - refusing to publish the draft build. "
              f"This target is a public repo.", file=sys.stderr)
        return 2
    if not (rendered / "index.html").exists():
        print(f"{rendered}/index.html not found - run `thesis-agent site` first",
              file=sys.stderr)
        return 2

    corpus_files: list[Path] = []
    if not args.site_only:
        corpus_files = [build / name for name in
                        ("corpus_public.md", "labels.json", "figures.json")]
        missing = [p for p in corpus_files if not p.exists()]
        if missing:
            print("missing from the build: " + ", ".join(str(p) for p in missing)
                  + " - run `thesis-agent build` first", file=sys.stderr)
            return 2

    try:
        _scan(sorted(p for p in rendered.rglob("*") if p.is_file()))
        _scan(corpus_files)
    except GuardFailure as exc:
        print(f"refusing to publish: {exc}", file=sys.stderr)
        return 2

    site_dest = target / args.subdir
    written = _copy_tree(rendered, site_dest)
    print(f"site    {written} files -> {site_dest}")

    if corpus_files:
        corpus_dest = target / args.subdir / "corpus"
        corpus_dest.mkdir(parents=True, exist_ok=True)
        for path in corpus_files:
            shutil.copy2(path, corpus_dest / path.name)
        print(f"corpus  {len(corpus_files)} files -> {corpus_dest}")

    (site_dest / "README.md").write_text(README.format(source=source), encoding="utf-8")

    print(f"\nNothing was committed. Review the diff in {target}, then commit and push "
          f"there yourself.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
